### PR TITLE
Add Local Government District (2021) to Health and Social Care Trust (2018) Lookup

### PR DESCRIPTION
**Pull request by MatteoLarrode**
Created a lookup table that associates Northern Ireland local authorities (local government districts) with their associated Health and Social Care Trust. The table has been documented.

This lookup table can be used to integrate data at the Health administration geography level to the HIE, using functions that could aggregate Local authorities metrics. 

LGDs and HSCTs are coterminuous in Northern Ireland: 

Screenshot 2023-07-06 at 11 27 19

Source: NISRA, Registrar General Annual Report 2015, Appendix 7

https://www.nisra.gov.uk/sites/nisra.gov.uk/files/publications/Maps-of-NI-Health-Trusts-and-Local-Government-Districts.pdf

### CODE REVIEW

**Review by MikeJohnPage — CHANGES_REQUESTED** [review]
Can we rename the files to use the 'ltla21' nomenclature, instead of 'lgd21'. For example `lookup_ltla21_hsct18.R`? This way it maintains consistency with the other data sets. I appreciate there is one inconsistency here with another data set, which I will file an issue to address at a later date.

**Comment by MikeJohnPage** [comment]
Thanks for the additional details and map. They are very helpful. Great work.

**Comment by MatteoLarrode** [comment]
Thank you for reviewing, I fixed the ltla inconsistencies, and corrected the type.

**Comment by MikeJohnPage** [comment]
Thanks. Merging now. Congrats on your first humaniverse contribution 🥳

**Pull request merged**
